language: ruby

env:
  global:
    - TRAVIS_NODE_VERSION="10"
    - DISCOURSE_HOSTNAME=www.example.com
    - RUBY_GLOBAL_METHOD_CACHE_SIZE=131072
    - DISCOURSE_PLUGIN=discourse-fingerprint

addons:
  chrome: stable
  postgresql: 9.6
  apt:
    update: true
    packages:
    - gifsicle
    - jpegoptim
    - optipng
    - jhead

matrix:
  fast_finish: true

rvm:
  - 2.5.1
  - 2.4.4

services:
  - redis-server

sudo: required
dist: trusty

cache:
  apt: true
  yarn: true
  directories:
    - vendor/bundle

before_install:
  - git clone --depth=1 https://github.com/discourse/discourse.git build && cd build
  - git clone --depth=1 -b $TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git plugins/$DISCOURSE_PLUGIN
  - nvm install node
  - node --version
  - gem install bundler
  - yarn global add eslint babel-eslint prettier

install:
  - bundle install --without development --deployment --retry=3 --jobs=3

before_script:
  - bundle exec rake db:create db:migrate

script:
  - bundle exec rubocop --parallel
  - eslint --ext .es6 plugins/$DISCOURSE_PLUGIN/assets/javascripts --ignore-pattern plugins/$DISCOURSE_PLUGIN/assets/javascripts/lib/fingerprintjs2.js.es6
  - bundle exec rake plugin:spec["$DISCOURSE_PLUGIN"]
